name: Build Image
description: Build and push Docker image by digest

inputs:
  platform:
    description: Platform i.e. "linux/amd64", "linux/arm64"
    required: true
  image-name:
    description: Name of the image
    required: true
  dockerfile:
    description: Dockerfile path
    required: true
  title:
    description: Custom image title (overrides repository name)
    required: false
  description:
    description: Custom image description (overrides repository description)
    required: false
  secrets:
    description: List of secrets to expose to the build
    required: false
  raw-tag:
    description: Raw tag value
    default: latest

runs:
  using: composite
  steps:

    - name: Prepare
      shell: bash
      run: |
        platform=${{ inputs.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Raw tag
      id: raw_tag
      uses: ASzc/change-string-case-action@v8
      with:
        string: ${{ inputs.raw-tag }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: ${{ inputs.image-name }}
        tags: |
          type=raw,event=workflow_dispatch,value=${{ steps.raw_tag.outputs.lowercase }}
        labels: |
          ${{ inputs.title != '' && format('org.opencontainers.image.title={0}', inputs.title) || '' }}
          ${{ inputs.description != '' && format('org.opencontainers.image.description={0}', inputs.description) || '' }}
        annotations: |
          ${{ inputs.title != '' && format('org.opencontainers.image.title={0}', inputs.title) || '' }}
          ${{ inputs.description != '' && format('org.opencontainers.image.description={0}', inputs.description) || '' }}

    - name: Build and push by digest
      id: build
      uses: docker/build-push-action@v7
      with:
        push: ${{ github.actor != 'dependabot[bot]' }}
        context: .
        file: ${{ inputs.dockerfile}}
        platforms: ${{ inputs.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        provenance: false
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true,oci-mediatypes=true
        cache-from: type=gha,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,mode=max,scope=${{ inputs.dockerfile }}-${{ env.PLATFORM_PAIR }}
        secrets: ${{ inputs.secrets }}

    - name: Export digest
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@v7
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
