name: Build PHP Images

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      platform:
        description: Platform i.e. "linux/amd64", "linux/arm64"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true
      dockerfile:
        description: Dockerfile path
        type: string
        default: Dockerfile
      title:
        description: Custom image title (overrides repository name)
        type: string
        required: false
      description:
        description: Custom image description (overrides repository description)
        type: string
        required: false
      secrets:
        description: List of secrets to expose to the build
        type: string
        required: false
      disable-apparmor:
        description: Disable AppArmor for the build
        type: boolean
        default: false

jobs:

  runtime:
    uses: ./.github/workflows/build.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      platform: ${{ inputs.platform }}
      dockerfile: ${{ inputs.dockerfile }}
      target: runtime
      image-name: ${{ inputs.image-name }}
      title: ${{ inputs.title }}
      description: ${{ inputs.description }}
      secrets: ${{ inputs.secrets }}
      disable-apparmor: ${{ inputs.disable-apparmor }}

  builder:
    uses: ./.github/workflows/build.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      platform: ${{ inputs.platform }}
      dockerfile: ${{ inputs.dockerfile }}
      target: builder
      image-name: ${{ inputs.image-name }}/builder
      title: ${{ inputs.title }}
      description: ${{ inputs.description }}
      secrets: ${{ inputs.secrets }}
      disable-apparmor: ${{ inputs.disable-apparmor }}

  builder_nodejs:
    uses: ./.github/workflows/build.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      platform: ${{ inputs.platform }}
      dockerfile: ${{ inputs.dockerfile }}
      target: builder_nodejs
      image-name: ${{ inputs.image-name }}/builder_nodejs
      title: ${{ inputs.title }}
      description: ${{ inputs.description }}
      secrets: ${{ inputs.secrets }}
      disable-apparmor: ${{ inputs.disable-apparmor }}
