name: Build PHP Images

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      platform:
        description: Platform i.e. "linux/amd64", "linux/arm64"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true
      dockerfile:
        description: Dockerfile path
        type: string
        default: Dockerfile
      title:
        description: Custom image title (overrides repository name)
        type: string
        required: false
      description:
        description: Custom image description (overrides repository description)
        type: string
        required: false
      secrets:
        description: List of secrets to expose to the build
        type: string
        required: false
      disable-apparmor:
        description: Disable AppArmor for the build
        type: boolean
        default: false

jobs:
  build:
    name: Build Image
    runs-on: ${{ inputs.runs-on }}
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v8
        with:
          string: ${{ inputs.image-name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Disable AppArmor
        if: ${{ inputs.disable-apparmor }}
        uses: cisagov/action-disable-apparmor@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push by digest (runtime)
        uses: specsnl/github-actions/build-image@2.0.0-rc.1
        with:
          dockerfile: ${{ inputs.dockerfile }}
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}
          target: runtime
          title: ${{ inputs.title }}
          description: ${{ inputs.description }}
          secrets: ${{ inputs.secrets }}

      - name: Build and Push by digest (builder)
        uses: specsnl/github-actions/build-image@2.0.0-rc.1
        with:
          dockerfile: ${{ inputs.dockerfile }}
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}/builder
          target: builder
          title: ${{ inputs.title }}
          description: ${{ inputs.description }}
          secrets: ${{ inputs.secrets }}

      - name: Build and Push by digest (builder_nodejs)
        uses: specsnl/github-actions/build-image@2.0.0-rc.1
        with:
          dockerfile: ${{ inputs.dockerfile }}
          platform: ${{ inputs.platform }}
          image-name: ${{ steps.image_name.outputs.lowercase }}/builder_nodejs
          target: builder_nodejs
          title: ${{ inputs.title }}
          description: ${{ inputs.description }}
          secrets: ${{ inputs.secrets }}
