name: Merge PHP images to manifest

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true
      title-runtime:
        description: Custom image title for runtime (overrides repository name)
        type: string
        required: false
      description-runtime:
        description: Custom image description for runtime (overrides repository description)
        type: string
        required: false
      title-builder:
        description: Custom image title for builder (overrides repository name)
        type: string
        required: false
      description-builder:
        description: Custom image description for builder (overrides repository description)
        type: string
        required: false
      title-builder_nodejs:
        description: Custom image title for builder_nodejs (overrides repository name)
        type: string
        required: false
      description-builder_nodejs:
        description: Custom image description for builder_nodejs (overrides repository description)
        type: string
        required: false
      raw-tag:
        description: Raw tag value
        type: string
        default: latest

jobs:

  runtime:
    uses: ./.github/workflows/merge.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      target: runtime
      image-name: ${{ inputs.image-name }}
      title: ${{ inputs.title-runtime }}
      description: ${{ inputs.description-runtime }}
      raw-tag: ${{ inputs.raw-tag }}

  builder:
    uses: ./.github/workflows/merge.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      target: builder
      image-name: ${{ inputs.image-name }}/builder
      title: ${{ inputs.title-builder }}
      description: ${{ inputs.description-builder }}
      raw-tag: ${{ inputs.raw-tag }}

  builder_nodejs:
    uses: ./.github/workflows/merge.yml
    with:
      runs-on: ${{ inputs.runs-on }}
      target: builder_nodejs
      image-name: |
        ${{ inputs.image-name }}/builder_nodejs
        ${{ inputs.image-name }}/node
      title: ${{ inputs.title-builder_nodejs }}
      description: ${{ inputs.description-builder_nodejs }}
      raw-tag: ${{ inputs.raw-tag }}
