name: Merge PHP images to manifest

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runner name i.e. default runner "ubuntu-24.04"
        type: string
        required: true
      image-name:
        description: Image name
        type: string
        required: true
      title-runtime:
        description: Custom image title for runtime (overrides repository name)
        type: string
        required: false
      description-runtime:
        description: Custom image description for runtime (overrides repository description)
        type: string
        required: false
      title-builder:
        description: Custom image title for builder (overrides repository name)
        type: string
        required: false
      description-builder:
        description: Custom image description for builder (overrides repository description)
        type: string
        required: false
      title-builder_nodejs:
        description: Custom image title for builder_nodejs (overrides repository name)
        type: string
        required: false
      description-builder_nodejs:
        description: Custom image description for builder_nodejs (overrides repository description)
        type: string
        required: false
      raw-tag:
        description: Raw tag value
        type: string
        default: latest

jobs:
  merge:
    name: Merge Images
    runs-on: ${{ inputs.runs-on }}
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v7

      - name: Image name
        id: image_name
        uses: ASzc/change-string-case-action@v8
        with:
          string: ${{ inputs.image-name }}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Create Manifest (runtime)
        uses: specsnl/github-actions/create-manifest@2.1.0
        with:
          image-name: ${{ steps.image_name.outputs.lowercase }}
          target: runtime
          description: ${{ inputs.description-runtime }}
          title: ${{ inputs.title-runtime }}
          raw-tag: ${{ inputs.raw-tag }}

      - name: Create Manifest (builder)
        uses: specsnl/github-actions/create-manifest@2.1.0
        with:
          image-name: ${{ steps.image_name.outputs.lowercase }}/builder
          target: builder
          description: ${{ inputs.description-builder }}
          title: ${{ inputs.title-builder }}
          raw-tag: ${{ inputs.raw-tag }}

      - name: Create Manifest (builder_nodejs)
        uses: specsnl/github-actions/create-manifest@2.1.0
        with:
          image-name: |
            ${{ steps.image_name.outputs.lowercase }}/builder_nodejs
            ${{ steps.image_name.outputs.lowercase }}/node
          target: builder_nodejs
          description: ${{ inputs.description-builder_nodejs }}
          title: ${{ inputs.title-builder_nodejs }}
          raw-tag: ${{ inputs.raw-tag }}
